### ISSUE TITLE
Expose as a lib

### ISSUE THREAD

**Issue by thom4parisot** [DTrejo/readmetree#7]
Hello, excellent idea :-)

Here is a small suggestion: extracting the tree walk to be able to require your module in some other way. Your CLI program would self-consume it.

So as we could do:

``` js
var rtree = require('readmetree');

rtree.find('node_modules/my-namespace*', { flatten: true }, function(readmes){
  readmes.forEach(function(readme){
    //now do stuff with the readme
    //readme.getContent();  // returns a String content
    //readme.getBuffer(); // returns a Buffer object
    //readme.getStream(); // returns a stream object
  });
});
```

Based on that, cool stuff could be done (like `rtree.toc` to generate a global TOC etc.).

**Comment by DTrejo** [comment]
Hi Thomas thanks for the suggestion - are you wanting to use this as a
library in a project?

D

## 

Please excuse any brevity

**Comment by thom4parisot** [comment]
Potentially it could be. But if I don't, others will do.

I just bumped on your project while [presenting a talk on README](https://oncletom.io/talks/2014/writethedocs/) and @nfroidure coined your project :-)

It can be useful if a project is split in smaller modules among the time, in case you want to filter out non-wanted dependencies (I don't want the README of grunt or of any npm modules whereas I might want to generate a consolidated README of all subprojects; for a gh-pages converted to HTML website for example).

That's a very condensed view of the use cases of your lib I see ;-)
